# fly.toml app configuration file generated for backend-server-1 on 2023-12-15T13:22:04-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-server-1"
primary_region = "bog"

[build]

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
